[package]
name = "demo01"
version = "0.1.0"
edition = "2021"

[workspace]
[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.95"

[dependencies.web-sys]
version = "0.3.35"
features = [
    "console",
]
