[package]
name = "demo14-sqlx"
version = "0.1.0"
edition = "2024"

[dependencies]

sqlx = { path = "../../deps/sqlx", features = ["postgres", "runtime-tokio"]}
tokio = { version = "1.47.1", features = ["full"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"